name: Build Matrix

on:
  pull_request:
  push:

jobs:
  windows-build:
    runs-on: [windows-latest]
    name: Validation
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run validation
      run: |
        KatEngine -validate -mod TGC.mod
